services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    user: 'node'
    working_dir: /app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - python
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: 'npm start'

  python:
    build:
      context: .
      dockerfile: /stock_api/Dockerfile
    working_dir: /app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    command: python3 stock_api/server.py

volumes:
  group-project:
